### ISSUE TITLE
$auth

### ISSUE THREAD

**Issue by khuumi** [ColumbiaJS/generator-columbia-angular#36]
I am looking through the code and having a hard time figuring out where $auth comes in and where it is defined? Is this an angular module?

**Comment by levbrie** [comment]
@khuumi $auth is actually one of the services [satellizer](https://github.com/sahat/satellizer) provides.  Actually, one of the reasons that it's become a best practice not to start services or methods with the `$` now is precisely because it makes people think it's an angular service - this probably should have been called something else by Sahat.  In any case, you can [check out the satellizer documentation](https://github.com/sahat/satellizer) for more on how this works.  Much of the setup I have on the server is just an extension of what he has in his node example.
